---
- hosts: development
  user: vagrant
  sudo: true
  vars_files:
    - group_vars/development.yml
  roles:
    - { role: common, tags: ['initial']}
    - { role: mongo, tags: ['deps', 'mongo']}
    - { role: redis, tags: ['deps', 'redis']}
    - { role: nodejs, tags: ['deps', 'nodejs']}
    - { role: texlive, tags: ['deps', 'texlive']}
    - { role: sharelatex, tags: ['sharelatex']}